### ISSUE TITLE
Migrate website repo https://git.eclipse.org/c/www.eclipse.org/pde.git/ to github

### ISSUE THREAD

**Issue by merks** [eclipse-pde/.github#1]
This repo serves the content of the project site https://www.eclipse.org/pde/

This is similar to the following issue:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/168

**Comment by sravanlakkimsetti** [comment]
As of now publishing happens using gerrit repos. Lets postpone migration of these repos till we have a solution to publish from github.

**Comment by akurtakov** [comment]
Webmaster did the migration and it's hosted at https://github.com/eclipse-pde/pde-website now.
