### ISSUE TITLE
Doc link in organization README leads nowhere

### ISSUE THREAD

**Issue by thahnen** [eclipse-pde/.github#7]
The outgoing link to the PDE documentation [HERE](https://github.com/eclipse-pde/.github/blob/main/profile/README.md?plain=1#L30) and even the proposed but not merged pull request [HERE](https://github.com/eclipse-pde/.github/pull/5) lead nowhere. Please fix this with the correct link.

**Comment by mickaelistria** [comment]
Thanks for reporting. This doc bundle was moved recently inside the main PDE repo: https://github.com/eclipse-pde/eclipse.pde/tree/master/org.eclipse.pde.doc.user . Can you please submit the PR to fix the doc?

**Comment by thahnen** [comment]
Sure
