### ISSUE TITLE
The README Page is out of date

### ISSUE THREAD

**Issue by opcoach** [eclipse-pde/.github#9]
In the main PDE readme page there is a list of pde components that are out of date 

PDE (core) : actualy contains all the pde project : both core and UI
PDE api : does not exists anymore
PDE build : moved in PDE -> should be explained in the pde repository. 
PDE website : has no read me page
PDE doc : seems to be the 'docs' folder in PDE -> should be in the pde repository? 

it seems that the PDE organization and the PDE repository are basically the same.. and there should be only one repository ... This is confusing

**Comment by vogella** [comment]
Just send a PR to fix it.
